apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: new-web
  template:
    metadata:
      labels:
        app: new-web
    spec:
      containers:
      - name: web
        image: nginx
        ports:
        - containerPort: 80
