apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: old-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort  # To expose the service on a port accessible externally
