apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80        # Port the service exposes internally
      targetPort: 80  # Port the container is listening on
      nodePort: 30001 # Port on each node to expose externally


