apiVersion: v1
kind: Service
metadata:
  name: multi-port-service
spec:
  selector:
    app: multi-port-app
  ports:
  - name: http   # Unique name for the HTTP port
    protocol: TCP
    port: 80     # Service Port for HTTP
    targetPort: 80  # Target containerPort in the deployment
  - name: https  # Unique name for the HTTPS port
    protocol: TCP
    port: 443    # Service Port for HTTPS
    targetPort: 443 # Target containerPort in the deployment

